baseURL = "https://joelabreurojas.github.io"
languageCode = "en-US"
title = "Joel Abreu Rojas"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Joel Abreu"
  description = "Code is measured by the time it takes to understand and use it, not by the number of lines."
  github = "joelabreurojas"
  linkedin = "joelabreurojas"
  email = "joelabreurojas@gmail.com"
  keywords = "Software Engineering, Database Design, Python, AI, Automation, Linux"
  rss = true
  userStatusEmoji = "👀"
  favicon = "/images/favicon.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/github-mark-white.png"
  location = "Puerto Ordaz, Venezuela"
