baseURL = "https://joelabreurojas.github.io"
languageCode = "en-US"
title = "Joel Abreu Rojas"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
author = "Joel Abreu Rojas"
description = "Software Engineer"
github = "joelabreurojas"
linkedin = "joelabreurojas"
email = "joelabreurojas@gmail.com"
keywords = "Software Engineer, Python, RAG, LLMs, LangChain, FastAPI, System Design, Architecture, AI Engineering"
rss = true
userStatusEmoji = "👀"
favicon = "/images/favicon.png"
avatar = "/images/avatar.png"
headerIcon = "/images/github-mark-white.png"
location = "Puerto Ordaz, Venezuela"
